# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor_A = torch.rand(7, 7)
tensor_A

tensor([[0.7436, 0.4663, 0.3138, 0.4370, 0.6995, 0.0353, 0.8591],
        [0.5255, 0.7614, 0.9886, 0.2713, 0.7093, 0.4616, 0.6177],
        [0.4096, 0.2167, 0.2187, 0.8823, 0.7500, 0.5874, 0.6069],
        [0.0363, 0.2128, 0.1430, 0.5894, 0.5565, 0.7971, 0.9089],
        [0.8063, 0.9633, 0.5225, 0.0984, 0.3907, 0.4756, 0.7197],
        [0.6760, 0.7383, 0.0489, 0.4082, 0.5509, 0.3195, 0.0665],
        [0.2946, 0.1118, 0.7468, 0.3008, 0.7491, 0.8243, 0.9533]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor_B = torch.rand(1, 7)

# Perform matrix multiplication
torch.mm(tensor_A, tensor_B.T)

tensor([[1.5258],
        [1.6338],
        [1.6059],
        [1.3628],
        [1.7842],
        [1.3567],
        [1.6935]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_C = torch.rand(7, 7)
tensor_D = torch.rand(1, 7)

# Matrix multiply tensors
torch.mm(tensor_C, tensor_D.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [31]:
# Set random_seed
torch.manual_seed(1234)

# Check for access to GPU,  Set random seed
if torch.cuda.is_available():
  device = "cuda"
else:
  device = "cpu"

print(f"Device: {device}")

# Create two random tensors on GPU
tensor_E = torch.rand(2, 3)
tensor_F = torch.rand(2, 3)
tensor_E = tensor_E.to(device)
tensor_F = tensor_F.to(device)
tensor_E, tensor_F

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [32]:
# Perform matmul on tensor_A and tensor_B
tensor_MM_GPU = torch.mm(tensor_E, tensor_F.T)
tensor_MM_GPU, tensor_MM_GPU.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [33]:
# Find max and min
tensor_MM_GPU.max(), tensor_MM_GPU.min()


(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [34]:
# Find arg max and min
tensor_MM_GPU.argmax(), tensor_MM_GPU.argmin()


(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [37]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_G = torch.rand(1, 1, 1, 10)
print({tensor_G, tensor_G.shape})

# Remove single dimensions
tensor_G = tensor_G.squeeze()

# Print out tensors and their shapes
print({tensor_G, tensor_G.shape})

{tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10])}
{tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10])}
